import {Component, NgZone, OnInit} from '@angular/core';
import * as am4core from '@amcharts/amcharts4/core';
import * as am4plugins_wordCloud from '@amcharts/amcharts4/plugins/wordCloud';

import am4themes_animated from '@amcharts/amcharts4/themes/animated';

am4core.useTheme(am4themes_animated);

@Component({
  selector: 'app-tagcloud',
  templateUrl: './tagcloud.component.html',
  styleUrls: ['./tagcloud.component.css']
})
export class TagcloudComponent implements OnInit {

  constructor(private zone: NgZone) { }

  ngOnInit() {
    this.zone.runOutsideAngular(() => {
      let chart = am4core.create('tagCloud', am4plugins_wordCloud.WordCloud);
      chart.fontFamily = "Courier New";
      let series = chart.series.push(new am4plugins_wordCloud.WordCloudSeries());
      series.randomness = 0.1;
      series.rotationThreshold = 0.5;

      series.data = [{"count":9389,"Hashtags":"#WHO"},
        {"count":1155,"Hashtags":"#PCAs"},
        {"count":991,"Hashtags":"#Yellowhammer"},
        {"count":960,"Hashtags":"#TheMusicVideo"},
        {"count":945,"Hashtags":"#DemDebate"},
        {"count":845,"Hashtags":"#BoyWithLuv"},
        {"count":637,"Hashtags":"#BiggBossTamil"},
        {"count":629,"Hashtags":"#bbcqt"},
        {"count":589,"Hashtags":"#BiggBoss"},
        {"count":572,"Hashtags":"#Kavin"},
        {"count":545,"Hashtags":"#पितृपूजा_निषेध"},
        {"count":504,"Hashtags":"#FridayFeeling?"},
        {"count":454,"Hashtags":"#Cheran"},
        {"count":448,"Hashtags":"#S…"},
        {"count":442,"Hashtags":"#…"},
        {"count":439,"Hashtags":"#DemDebate\n\nHow"},
        {"count":411,"Hashtags":"#5SOSxLateNight"},
        {"count":393,"Hashtags":"#RoaldDahlDay"},
        {"count":336,"Hashtags":"#iPhone11"},
        {"count":327,"Hashtags":"#AppleEvent"},
        {"count":308,"Hashtags":"#BTS"},
        {"count":300,"Hashtags":"#operationyellowhammer"},
        {"count":294,"Hashtags":"#강다니엘"},
        {"count":288,"Hashtags":"#remainernow"},
        {"count":264,"Hashtags":"#DemocraticDebate"},
        {"count":252,"Hashtags":"#LouDre"},
        {"count":248,"Hashtags":"#LeaveAlliance"},
        {"count":245,"Hashtags":"#kangdaniel"},
        {"count":225,"Hashtags":"#cpfc"},
        {"count":220,"Hashtags":"#win"},
        {"count":216,"Hashtags":"#KyutaeOppa"},
        {"count":209,"Hashtags":"#KPop"},
        {"count":209,"Hashtags":"#Gotoe"},
        {"count":209,"Hashtags":"#CreatorsZone\n\nWho"},
        {"count":209,"Hashtags":"#पितृपूजा_निषेध\nWho"},
        {"count":209,"Hashtags":"#KCON19TH!"},
        {"count":205,"Hashtags":"#SaveNallamala."},
        {"count":201,"Hashtags":"#BlueGirl"},
        {"count":185,"Hashtags":"#auspol"},
        {"count":184,"Hashtags":"#WIN"},
        {"count":177,"Hashtags":"#SwachhBharatStories."},
        {"count":176,"Hashtags":"#KillMyMind"},
        {"count":175,"Hashtags":"#V"},
        {"count":175,"Hashtags":"#FridayThe13th"},
        {"count":172,"Hashtags":"#BritishIndependence,"},
        {"count":167,"Hashtags":"#श्राद्ध_क्यों_करें\nShraadhs"},
        {"count":167,"Hashtags":"#ACA6"},
        {"count":162,"Hashtags":"#UniversalChildCare"},
        {"count":160,"Hashtags":"#FREEBIEFRIDAY"},
        {"count":159,"Hashtags":"#TheGroup"},
        {"count":158,"Hashtags":"#SandtonShutdown"},
        {"count":158,"Hashtags":"#KillMyMindMusicVideo?"},
        {"count":157,"Hashtags":"#NHL20"},
        {"count":156,"Hashtags":"#पितृपूजा_निषेध\nThose"},
        {"count":154,"Hashtags":"#RT"},
        {"count":152,"Hashtags":"#BeloBelleOfTheBall…"},
        {"count":151,"Hashtags":"#HongKong"},
        {"count":149,"Hashtags":"#findom"},
        {"count":148,"Hashtags":"#organic"},
        {"count":147,"Hashtags":"#sex"},
        {"count":146,"Hashtags":"#snacks"},
        {"count":146,"Hashtags":"#OrganicSeptember,"},
        {"count":145,"Hashtags":"#peoplesvote"},
        {"count":144,"Hashtags":"#SocialistAnyday"},
        {"count":143,"Hashtags":"#SineSandaan"},
        {"count":143,"Hashtags":"#KillMyMindMusicVideo"},
        {"count":142,"Hashtags":"#FinalSay"},
        {"count":141,"Hashtags":"#BrexitShambl…"},
        {"count":140,"Hashtags":"#EXO"},
        {"count":139,"Hashtags":"#ABSCBNBallFanFave"},
        {"count":136,"Hashtags":"#horny"},
        {"count":134,"Hashtags":"#Borderlands3"},
        {"count":131,"Hashtags":"#Brexit"},
        {"count":131,"Hashtags":"#blue_girl,"},
        {"count":130,"Hashtags":"#Tiwa4999"},
        {"count":129,"Hashtags":"#AlwaysFootballTime"},
        {"count":129,"Hashtags":"#BoyWithLuv\nhttps://t.co/tBwci17COP"},
        {"count":129,"Hashtags":"#BritishIndependence"},
        {"count":129,"Hashtags":"#PCAs\n#TheMusicVideo"},
        {"count":127,"Hashtags":"#KillThisLove"},
        {"count":125,"Hashtags":"#r4today"},
        {"count":125,"Hashtags":"#MobGiveaway"},
        {"count":124,"Hashtags":"#OurJooniverse"},
        {"count":122,"Hashtags":"#ATEEZ"},
        {"count":120,"Hashtags":"#Ou…"},
        {"count":119,"Hashtags":"#BBNaija"},
        {"count":118,"Hashtags":"#YangGang"},
        {"count":116,"Hashtags":"#TheConcertTour"},
        {"count":116,"Hashtags":"#Article149"},
        {"count":115,"Hashtags":"#LoveYo…"},
        {"count":114,"Hashtags":"#Bonehead,…"},
        {"count":114,"Hashtags":"#뷔"},
        {"count":113,"Hashtags":"#BiggBossTamil…"},
        {"count":112,"Hashtags":"#BiggBossTamilS3"},
        {"count":111,"Hashtags":"#HelpEach1"},
        {"count":109,"Hashtags":"#ADNLoveAndPeace"},
        {"count":109,"Hashtags":"#VIJAY"},
        {"count":109,"Hashtags":"#DemDebate:"},
        {"count":107,"Hashtags":"#UrbanNaxals"},
        {"count":106,"Hashtags":"#KashmirSolidarityJalsa"},
        {"count":105,"Hashtags":"#Karachi"},
        {"count":104,"Hashtags":"#Mugen"},
        {"count":103,"Hashtags":"#iKON"},
        {"count":103,"Hashtags":"#TeamIndia"},
        {"count":103,"Hashtags":"#방탄소년단"},
        {"count":103,"Hashtags":"#Xiumin"},
        {"count":103,"Hashtags":"#Peop…"},
        {"count":103,"Hashtags":"#IsaPaWithFeelings"},
        {"count":103,"Hashtags":"#아이콘…"},
        {"count":103,"Hashtags":"#Jinhwan"},
        {"count":100,"Hashtags":"#IndvsSA"},
        {"count":100,"Hashtags":"#JusticeForFUOYE"},
        {"count":99,"Hashtags":"#FreePuriDeitiesFromMafias."},
        {"count":98,"Hashtags":"#sugardaddy"},
        {"count":98,"Hashtags":"#Super30"},
        {"count":97,"Hashtags":"#climate"},
        {"count":96,"Hashtags":"#FridayFeeling"},
        {"count":96,"Hashtags":"#Denmark's"},
        {"count":96,"Hashtags":"#Boy…"},
        {"count":95,"Hashtags":"#Affinitweet"},
        {"count":94,"Hashtags":"#OddOneOut"},
        {"count":94,"Hashtags":"#nudes"},
        {"count":93,"Hashtags":"#OTD"},
        {"count":93,"Hashtags":"#पितृपूजा_निषेध\nShraadhs"},
        {"count":92,"Hashtags":"#FandomFriday"},
        {"count":92,"Hashtags":"#PL"},
        {"count":91,"Hashtags":"#JusticeForFUOYE:"},
        {"count":90,"Hashtags":"#PJMSelcaDay"},
        {"count":88,"Hashtags":"#JusticeForFUOYE."},
        {"count":88,"Hashtags":"#snacks…"},
        {"count":87,"Hashtags":"#missing"},
        {"count":85,"Hashtags":"#Darbar"},
        {"count":84,"Hashtags":"#TheSocialCelebrity"},
        {"count":83,"Hashtags":"#Tharshan…"},
        {"count":82,"Hashtags":"#Thala"},
        {"count":81,"Hashtags":"#पितृपूजा_निषेध\n"},
        {"count":81,"Hashtags":"#quote"},
        {"count":80,"Hashtags":"#BiggBossTamil3"},
        {"count":80,"Hashtags":"#TaylorSwift"},
        {"count":80,"Hashtags":"#RemainerNow"},
        {"count":79,"Hashtags":"#DemDebate,"},
        {"count":79,"Hashtags":"#DemDebate\n\nTwo"},
        {"count":78,"Hashtags":"#Superstar"},
        {"count":78,"Hashtags":"#Ajith"},
        {"count":78,"Hashtags":"#Sittrarasu"},
        {"count":77,"Hashtags":"#kavin"},
        {"count":77,"Hashtags":"#Kashmir"},
        {"count":75,"Hashtags":"#yanggang"},
        {"count":75,"Hashtags":"#Banners"},
        {"count":74,"Hashtags":"#paypig"},
        {"count":74,"Hashtags":"#TrueWarriors"},
        {"count":74,"Hashtags":"#Kajol"},
        {"count":74,"Hashtags":"#Sharukh"},
        {"count":73,"Hashtags":"#JohnBercow"},
        {"count":73,"Hashtags":"#JusticeForMariane"},
        {"count":72,"Hashtags":"#dilwaledulhanialejayenge."},
        {"count":72,"Hashtags":"#FIBAWC"},
        {"count":71,"Hashtags":"#TBT"},
        {"count":71,"Hashtags":"#엑소\n@layzhang"},
        {"count":71,"Hashtags":"#Hongkong"},
        {"count":71,"Hashtags":"#UCL"},
        {"count":69,"Hashtags":"#LoveYours…"},
        {"count":69,"Hashtags":"#EU"},
        {"count":69,"Hashtags":"#POTUS"},
        {"count":68,"Hashtags":"#ad"},
        {"count":68,"Hashtags":"#China,"},
        {"count":68,"Hashtags":"#ALDUBxADNMalagungAldo"},
        {"count":68,"Hashtags":"#OurPreciousSEHUN"},
        {"count":67,"Hashtags":"#BorisLiedToTheQueen."},
        {"count":67,"Hashtags":"#Thalapathy"},
        {"count":67,"Hashtags":"#DemDebate3"},
        {"count":65,"Hashtags":"#subway/rail"},
        {"count":65,"Hashtags":"#NeverForget\nRest"},
        {"count":65,"Hashtags":"#MTR,"},
        {"count":65,"Hashtags":"#FF"},
        {"count":65,"Hashtags":"#BetterTogether"},
        {"count":64,"Hashtags":"#박…"},
        {"count":64,"Hashtags":"#hedgehogs."},
        {"count":64,"Hashtags":"#Yeri"},
        {"count":64,"Hashtags":"#KimHeechul"},
        {"count":64,"Hashtags":"#Moto2"},
        {"count":63,"Hashtags":"#ARMY"},
        {"count":62,"Hashtags":"#XenophobicAttacks"},
        {"count":62,"Hashtags":"#teen"},
        {"count":61,"Hashtags":"#China"},
        {"count":61,"Hashtags":"#KatieHopkins"},
        {"count":61,"Hashtags":"#TheFemaleArtist"},
        {"count":61,"Hashtags":"#Bambam"},
        {"count":61,"Hashtags":"#BLACKPI…"},
        {"count":61,"Hashtags":"#Sana"},
        {"count":59,"Hashtags":"#श्राद्ध_क्यों_करें\nBy"},
        {"count":59,"Hashtags":"#WorldCup"},
        {"count":59,"Hashtags":"#Azzurri"},
        {"count":59,"Hashtags":"#mufc"},
        {"count":58,"Hashtags":"#cum"},
        {"count":58,"Hashtags":"#realmeXT"},
        {"count":58,"Hashtags":"#sellingnudes"},
        {"count":58,"Hashtags":"#goals\n🥇"},
        {"count":58,"Hashtags":"#WorldSepsisDay"},
        {"count":58,"Hashtags":"#TaeyongStreamingParty\n\nplaylist"}
      ];

      series.dataFields.word = "Hashtags";
      series.dataFields.value = "count";

      series.heatRules.push({
        "target": series.labels.template,
        "property": "fill",
        "min": am4core.color("#0000CC"),
        "max": am4core.color("#CC00CC"),
        "dataField": "value"
      });

      series.labels.template.urlTarget = "_blank";
      series.labels.template.tooltipText = "{word}: {value}";

      let hoverState = series.labels.template.states.create("hover");
      hoverState.properties.fill = am4core.color("#FF0000");

      let subtitle = chart.titles.create();

      let title = chart.titles.create();
      title.text = "Most Popular Tags";
      title.fontSize = 22;
      title.fontWeight = "800";
    });
  }
}
